### Find authors
GET http://localhost:8080/api/authors


### Find all articles
GET http://localhost:8080/api/articles

### Find an article 
GET http://localhost:8080/api/articles?authorNames=Tigran

### Empty result
GET http://localhost:8080/api/articles?authorNames=Arthur

### 404 user not found
GET http://localhost:8080/api/articles?authorNames=JohnDoe

### Article detail
GET http://localhost:8080/api/articles/2
